### ISSUE TITLE
Web installer fail

### ISSUE THREAD

**Issue by eried** [sukesh-ak/ESP32-TUX#18]
Hi! I am trying to test this using the web installer on sc01 plus but I get:
`Failed to initialize. Try resetting your device or holding the BOOT button while clicking INSTALL.`

I only have a reset button, is there is something simple I am failing to do?

**Comment by sukesh-ak** [comment]
This is an issue related to ESP32-S3 with native USB support.
You can join here on our fb group where people have provided workarounds for this issue.
https://www.facebook.com/groups/5303789986299456

Alternatively, I would suggest to get the debugger for WT32-SC01 Plus from the link in the readme of this repo.
This will ease the pain.

**Comment by sukesh-ak** [comment]
@eried Here is the short answer
![image](https://user-images.githubusercontent.com/53081362/213865093-233c4051-54f9-4d78-a19f-85be4231d8d5.png)

**Comment by eried** [comment]
Oh brilliant, thanks a lot!
