### ISSUE TITLE
WT32-SC01 - Only shows a white screen

### ISSUE THREAD

**Issue by ericjmonson** [sukesh-ak/ESP32-TUX#24]
I've gotten the demo to work great for a WT32-SC01+ board. However, when I follow the following video step by step, I end up with just a white screen on the display after flashing:
https://asciinema.org/a/549415

I have set the board up in "idf.py menuconfig" AS A "Wireless-Tag WT32-SC01" ... see the screen scrape from idf.py menuconfig:

```
(Top) → ESP32-TUX Configuration → Device Config
                                                                                             Espressif IoT Development Framework Configuration
    <choice TUX_DEVICE_SELECTED> Select the device (Wireless-Tag WT32-SC01 - SPI - 4MB Flash)  --->
(partitions/partition-4MB.csv) <PARTITION_TABLE_CUSTOM_FILENAME> Custom Partition CSV filename
    <choice ESPTOOLPY_FLASHSIZE> Flash size (4 MB)  --->
[*] <WALLPAPER_IMAGE> Enable wallpaper image

```

I'll also note that I compiled ESP32-TUX with the following version of IDF:
ESP-IDF v5.1-dev-2633-g8464186e67

**Comment by sukesh-ak** [comment]
@ericjmonson 
Can you try flashing your device from the following URL for testing?
https://tux.sukesh.me

Also, if you have compiled for Plus version, please make sure to delete the build folder and start fresh since the target device settings might be wrong.
`WT32-SC01` uses ESP32
`WT32-SC01 Plus` uses ESP32-S3

I would suggest, you use a released version of ESP-IDF since the main branch of the repo is a moving target and is expected to have breaking changes.

**Comment by ericjmonson** [comment]
That web installer is pretty slick. Unfortunately, though, I still only see a white screen after flashing with your version. I happen to have a handful of the WT32-SC01 (original ... not plus) devices, so I tried it on two different models. Both end up with just a white screen after flashing.

As for building, I was worried about artifacts lying around. I did a completely fresh clone of the git repo, made sure the esp32 was set for the build target, followed the video for setting up the partitions and selecting the device. I end up with a white screen when I compile on my own.

**Comment by sukesh-ak** [comment]
> That web installer is pretty slick. Unfortunately, though, I still only see a white screen after flashing with your version. I happen to have a handful of the WT32-SC01 (original ... not plus) devices, so I tried it on two different models. Both end up with just a white screen after flashing.
> 
> As for building, I was worried about artifacts lying around. I did a completely fresh clone of the git repo, made sure that esp32 was set as the build target, followed the video for setting up the partitions and selecting the device. I end up with a white screen when I compile on my own.

I will test and revert.

**Comment by gjm19761** [comment]
i have exactly same issue wt32-sc01 and get white screen after flashing and reboot, and using web installer

**Comment by sukesh-ak** [comment]
> i have exactly same issue wt32-sc01 and get white screen after flashing and reboot, and using web installer

Will check and update tomorrow. Sorry for the delay.

**Comment by sukesh-ak** [comment]
Update: @ericjmonson & @gjm19761 

I just flashed my WT32-SC01 device with firmware from https://tux.sukesh.me
And it works perfectly fine as expected.

So possible reasons for you not working
- Wrong device?
- Device specs have changed (like display controller)
- Not genuine device?

Can't think of any other reason :(

If you haven't checked yet, please flash from this website using 1st option and check.
https://tux.sukesh.me

**Comment by gjm19761** [comment]
same issue using  first option on website, my device isnt a new one (i bought it last year) , mine is a wt32-sc01-v3.2

**Comment by sukesh-ak** [comment]
> same issue using first option on website, my device isnt a new one (i bought it last year) , mine is a wt32-sc01-v3.2

You can check with this older sample without LVGL `using the code in the README`.
https://github.com/sukesh-ak/LVGL8-WT32-SC01-Arduino

**Comment by ericjmonson** [comment]
Sorry for the sideways video ... but so you can see it happening in action:
https://www.youtube.com/watch?v=91B7wnW03ww

I definately picked the correct one. I also have a wt32-sc01-v3.2 (as you'll see from the video).

I compiled and flashed the arduino version above (https://github.com/sukesh-ak/LVGL8-WT32-SC01-Arduino#touch-and-draw-sample-without-lvgl). When it starts up, the screen flashes white then black a number of times, then eventually just turns black.

**Comment by sukesh-ak** [comment]
> Sorry for the sideways video ... but so you can see it happening in action: https://www.youtube.com/watch?v=91B7wnW03ww
> 
> I definately picked the correct one. I also have a wt32-sc01-v3.2 (as you'll see from the video).
> 
> I compiled and flashed the arduino version above (https://github.com/sukesh-ak/LVGL8-WT32-SC01-Arduino#touch-and-draw-sample-without-lvgl). When it starts up, the screen flashes white then black a number of times, then eventually just turns black.

Can you check this from Arduino?
Please install `LovyanGFX` library and select `ESP32 Dev` Module for devices.

https://gist.github.com/sukesh-ak/a00d4c7d41a469d341972b3727e5029e

**Comment by ericjmonson** [comment]
Yeah ... as I mentioned above, I did install LovyanGFS in the Ardunio IDE and selected ESP32 Dev as the board. That's where I get the black and white flashes followed by a black screen.

**Comment by sukesh-ak** [comment]
> Yeah ... as I mentioned above, I did install LovyanGFS in the Ardunio IDE and selected ESP32 Dev as the board. That's where I get the black and white flashes followed by a black screen.

ok try the above snippet I just created to narrow down the issue.

**Comment by ericjmonson** [comment]
Flashing the above application, I end up with a white screen.

https://gist.github.com/sukesh-ak/a00d4c7d41a469d341972b3727e5029e

**Comment by ericjmonson** [comment]
Well ... good news. Been playing around with this today. Was able to get it working with my version of the boards. Had to change one line:
main/devices/conf_WT32SCO1.h
Line 81: cfg.freq_write = 80000000; // SPI clock on transmission (up to 80MHz, rounded to 80MHz divided by integer)
Changed to: cfg.freq_write = 40000000;

Now its all working. Not sure if there is more noise on the line making the SPI bus unstable at that clock speed, or why I had to drop the SPI clock speed.

**Comment by gjm19761** [comment]
cool  where is that file? i suspect wireless tag released a different version of the sc01 so now theres another variantto deal with

**Comment by gjm19761** [comment]
> Well ... good news. Been playing around with this today. Was able to get it working with my version of the boards. Had to change one line: main/devices/conf_WT32SCO1.h Line 81: cfg.freq_write = 80000000; // SPI clock on transmission (up to 80MHz, rounded to 80MHz divided by integer) Changed to: cfg.freq_write = 40000000;
> 
> Now its all working. Not sure if there is more noise on the line making the SPI bus unstable at that clock speed, or why I had to drop the SPI clock speed.

Can confirm this also fixed mine, will this be added to the web installer as suspect theres been a revision of the sc01

**Comment by sukesh-ak** [comment]
Glad you guys got it sorted it out :)

**Comment by jrversteegh** [comment]
@sukesh-ak This issue was closed, but not fixed?

**Comment by sukesh-ak** [comment]
> @sukesh-ak This issue was closed, but not fixed?

Haven't got time to confirm if that's the fix since it was working fine on my device.
Currently too busy to get all the devices checked again since ESP-IDF versions are being updated as well.

**Comment by jrversteegh** [comment]
@sukesh-ak OK, fair enough. Thanks for a great template!

But maybe leave the issue open (and potentially ask for a pull request to fix it if you don't have time yourself) rather than close the issue without a fix? I was at least confused, because I expected it to be fixed when it wasn't..
In either case, I can confirm the issue on wt32-sc01-v3.2. What version is "your device"?
