### ISSUE TITLE
Include Path errors

### ISSUE THREAD

**Issue by fnandomaia** [sukesh-ak/ESP32-TUX#29]
Hello.
I´m using Visual Studio Code. 
The code is building fine, but I see errors as shown bellow.
What´s the directory I need to set in INCLUDE PATH for  C++ Extension, or is there any configuration to fix these errors? 

![20230516-221047-001](https://github.com/sukesh-ak/ESP32-TUX/assets/5240596/9374e704-361d-4eae-9dd7-9741134168c2)
![20230516-221125-002](https://github.com/sukesh-ak/ESP32-TUX/assets/5240596/271b4b4a-5cd5-42f9-9644-5b7a6f6f545e)

**Comment by sukesh-ak** [comment]
I think your ESP-IDF vscode extension is not configured properly. 

You can goto extension settings and rerun the configuration.

**Comment by fnandomaia** [comment]
Fixed including full path of includes. 

Before:
#include "OpenWeatherMap.hpp"
After:
#include "../components/OpenWeatherMap/include/OpenWeatherMap.hpp"
