### ISSUE TITLE
MQTT implementation

### ISSUE THREAD

**Issue by fnandomaia** [sukesh-ak/ESP32-TUX#30]
I'm trying to implement the MQTT protocol inside an ESP32-TUX instance.

1. I enabled MQTT configuration inside idf.py menuconfig.

2. main.hpp I put the include of the local file for the mqtt library downloaded from Github (https://github.com/espressif/esp-mqtt) because that way it didn't give error of include not found.

3. main.hpp include mqtt_client.h file. I initialized the functions: mqtt_event_handler() and mqtt_app_start().
![20230517-192556-003](https://github.com/sukesh-ak/ESP32-TUX/assets/5240596/c894b794-df3f-4177-a56b-5cfdc30c8b0c)

4. main.cpp I placed the respective functions from the previous step and initialized mqtt_app_start().
![20230517-192517-002](https://github.com/sukesh-ak/ESP32-TUX/assets/5240596/37c2a0f8-b046-4870-a04a-3cfd655950d8)

5. It happens that when compiling it gives an error inside the mqtt_client.h library, as shown in the image below.
![20230517-192407-001](https://github.com/sukesh-ak/ESP32-TUX/assets/5240596/f0cdd2e8-19d0-4a14-b595-f7fecc1e1293)

I wonder if anyone has an idea of how to make it work or an example of working MQTT (connect, subscribe, publish) code.

Thanks!

**Comment by sukesh-ak** [comment]
@fnandomaia Please try to get MQTT working outside of ESP32-TUX so its easier to integrate after that.

IDF official repo is here
https://github.com/espressif/esp-mqtt
