### ISSUE TITLE
Question again if a port for Arduino IDE would be possible/feasible and some hint would be also possible 

### ISSUE THREAD

**Issue by knopserl** [sukesh-ak/ESP32-TUX#31]
this is a great project for the WT32-SC01 Plus, many thanks for shaing this!
But I also wanted to use it in the Arduino IDE.
It it feasible and worth to spent the effort to migrate this ESP-IDF based code to an Arduino IDE acceppted code?
I have tried to insert the main.cpp code in the "voide setup() function and an empto loop function (as I have not seen a matching or required loop code) and it does of course not compile because it does not even accept the include files such as #include <spi_flash_mmap.h> ?
Any help possible or to much to change?

**Comment by sukesh-ak** [comment]
I have explained the difference between ESP-IDF and Arduino here https://github.com/sukesh-ak/ESP32-TUX/issues/19

ESP32-TUX is built using ESP-IDF framework. 

If you want Arduino code to get you started, you can check this sample gist.
https://gist.github.com/sukesh-ak/610508bc84779a26efdcf969bf51a2d1
