### ISSUE TITLE
and compile issue

### ISSUE THREAD

**Issue by SoniaZotz** [sukesh-ak/ESP32-TUX#37]
E:\__test\ESP32-TUX\components\ota\ota.h:4:10:[m[K [01;31m[Kfatal error: [m[K../main/events/tux_events.hpp: No such file or directory
    4 | #include [01;31m[K"../main/events/tux_events.hpp"[m[K
      |          [01;31m[K^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
![Snag_2bc3f7d](https://github.com/sukesh-ak/ESP32-TUX/assets/10633874/6f47f51c-2a0c-49e7-8b25-3c439b34fed8)

**Comment by sukesh-ak** [comment]
Please check the video in the repo readme to learn how to compile.
You are probably using very old version of IDF i.e 3.x
