### ISSUE TITLE
dtill issies - why is this so difficult 

### ISSUE THREAD

**Issue by SoniaZotz** [sukesh-ak/ESP32-TUX#38]
Espressif/frameworks/esp-idf-v5.1.1-3/components/xtensa
-- --------------Compile Info------------
-- IDF_PATH = C:/Espressif/frameworks/esp-idf-v5.1.1-3
-- IDF_TARGET = esp32s3
-- PROJECT_NAME = ESP32-TUX
-- PROJECT_DIR = E:/__dev/ESP32-TUX
-- BUILD_DIR = E:/__dev/ESP32-TUX/build
-- SDKCONFIG = E:/__dev/ESP32-TUX/sdkconfig
-- SDKCONFIG_DEFAULTS = E:/__dev/ESP32-TUX/sdkconfig.defaults
-- CONFIG_LV_CONF_SKIP =
-- ---------------------------------------
-- CMAKE_SOURCE_DIR = E:/__dev/ESP32-TUX
-- CMAKE_BINARY_DIR = E:/__dev/ESP32-TUX/build
-- ---------By Sukesh Ashok Kumar---------
-- Configuring done
-- Generating done
-- Build files have been written to: E:/__dev/ESP32-TUX/build

E:/__dev/ESP32-TUX/components/LovyanGFX/src/lgfx/v1/platforms/esp32/common.cpp: In function 'void lgfx::v1::i2c::i2c_set_cmd(i2c_dev_t*, uint8_t, uint8_t, uint8_t)':
E:/__dev/ESP32-TUX/components/LovyanGFX/src/lgfx/v1/platforms/esp32/common.cpp:643:14: error: 'struct i2c_dev_t' has no member named 'comd0'; did you mean 'comd'?
  643 |       (&dev->comd0)[index].val = cmd_val;
      |              ^~~~~
      |              comd
ninja: build stopped: subcommand failed.
ninja failed with exit code 1, output of the command is in the E:\__dev\ESP32-TUX\build\log\idf_py_stderr_output_31640 and E:\__dev\ESP32-TUX\build\log\idf_py_stdout_output_31640
PS E:\__dev\ESP32-TUX>

#if defined (CONFIG_IDF_TARGET_ESP32S3)
      (&dev->comd0)[index].val = cmd_val;
#else
      dev->command[index].val = cmd_val;
#endif
    }

**Comment by sukesh-ak** [comment]
> E:/__dev/ESP32-TUX/components/LovyanGFX/src/lgfx/v1/platforms/esp32/common.cpp:643:14: error: 'struct i2c_dev_t' has no member named 'comd0'; did you mean 'comd'?
> 643 | (&dev->comd0)[index].val = cmd_val;

Error is coming from LovyanGFX library. So not sure. You need to check on their github repo
`
E:/__dev/ESP32-TUX/components/LovyanGFX/src/lgfx/v1/platforms/esp32/common.cpp:643:14: error: 'struct i2c_dev_t' has no member named 'comd0'; did you mean 'comd'?
643 | (&dev->comd0)[index].val = cmd_val;
`

Also make sure you are using released version of `ESP-IDF` and not from the main branch which is the working branch.
