### ISSUE TITLE
Please confirm the compile

### ISSUE THREAD

**Issue by SoniaZotz** [sukesh-ak/ESP32-TUX#40]

**Comment by sukesh-ak** [comment]
It was built with ESP-IDF 5. If you have newer SDK version, there might be breaking changes in the SDK.

Currently I don't have time to upgrade IDF and test. 
From your output I see `deprecated` messages which means IDF has breaking changes which needs to be fixed.

**Comment by SoniaZotz** [comment]
https://github.com/SoniaZotz/ESP32-TUX
