### ISSUE TITLE
Hardware display rotation

### ISSUE THREAD

**Issue by THE-KONDRAT** [sukesh-ak/ESP32-TUX#43]
Hi. I want to set default orientation as landscape.
I tried to change conf_WT32SCO1.h (width and height in defines) and helper_display.hpp (lcd.setRotation(3 instead of 2) ). Orientation changes but display width crops by 320 pixels.
I using WT32-SC01.
How can i change display orientation?

**Comment by sukesh-ak** [comment]
> Hi. I want to set default orientation as landscape. I tried to change conf_WT32SCO1.h (width and height in defines) and helper_display.hpp (lcd.setRotation(3 instead of 2) ). Orientation changes but display width crops by 320 pixels. I using WT32-SC01. How can i change display orientation?

Display default orientation is setup here. Try changing and see if it works for your requirements
https://github.com/sukesh-ak/ESP32-TUX/blob/37822a7b6dfcb67e278c78b2aa468817b6fa0bbe/main/helpers/helper_display.hpp#L91

**Comment by THE-KONDRAT** [comment]
With `lcd.setRotation(2)` display orientation is portrait.
![20231027_184529](https://github.com/sukesh-ak/ESP32-TUX/assets/87300126/faa7ebe0-7829-46a7-b3ea-67c83788a0e8)

With `lcd.setRotation(1)` display orientation is landscape but with black area on the right.
![20231027_185728](https://github.com/sukesh-ak/ESP32-TUX/assets/87300126/043c0698-5de4-411f-90eb-333dab8ad43f)

If i rotate display (with `lcd.setRotation(2)`) from ui it works.
How can i fix that?

**Comment by sukesh-ak** [comment]
> With `lcd.setRotation(2)` display orientation is portrait. ![20231027_184529](https://user-images.githubusercontent.com/87300126/278697475-faa7ebe0-7829-46a7-b3ea-67c83788a0e8.jpg)
> 
> With `lcd.setRotation(1)` display orientation is landscape but with black area on the right. ![20231027_185728](https://user-images.githubusercontent.com/87300126/278697832-043c0698-5de4-411f-90eb-333dab8ad43f.jpg)
> 
> If i rotate display (with `lcd.setRotation(2)`) from ui it works. How can i fix that?

Background image needs to be changed to cover the side. 
Guess you figured that out yourself.

**Comment by THE-KONDRAT** [comment]
Ok. I temporary disabled background image, but the black area still exists. Looks like the image width is 320 pix instead of 480.

**Comment by sukesh-ak** [comment]
> It works. I changed the width and height in helper and set rotation 1 instead of 3. And i set sw_rotate=0. But it doesn't look right. Is there another way to rotate the picture?

You might need 2 images, one for each orientation and dynamically load it.
