### ISSUE TITLE
Build error for SC-01 plus

### ISSUE THREAD

**Issue by maciek252** [sukesh-ak/ESP32-TUX#53]
Worked fine for SC-01, but for plus I'm getting:

Wdeprecated-enum-enum-conversion]
   94 |     lv_obj_remove_style(obj, NULL, LV_PART_ANY | LV_STATE_ANY);
      |                                    ~~~~~~~~~~~~^~~~~~~~~~~~~~
In file included from /home/maciek/d/ESP32-TUX/main/main.hpp:65:
/home/maciek/d/ESP32-TUX/main/helpers/helper_storage.hpp: In function 'bool init_sdspi()':
/home/maciek/d/ESP32-TUX/main/devices/conf_WT32SCO1-Plus.h:37:23: error: 'GPIO_NUM_41' was not declared in this scope; did you mean 'GPIO_NUM_4'?
   37 | #define SD_CS         GPIO_NUM_41
      |                       ^~~~~~~~~~~
/home/maciek/d/ESP32-TUX/main/devices/conf_WT32SCO1-Plus.h:37:23: note: in definition of macro 'SD_CS'
   37 | #define SD_CS         GPIO_NUM_41
      |                       ^~~~~~~~~~~
/home/maciek/d/ESP32-TUX/main/devices/conf_WT32SCO1-Plus.h:35:23: error: 'GPIO_NUM_40' was not declared in this scope; did you mean 'GPIO_NUM_4'?
   35 | #define SD_MOSI       GPIO_NUM_40
      |                       ^~~~~~~~~~~
/home/maciek/d/ESP32-TUX/main/devices/conf_WT32SCO1-Plus.h:35:23: note: in definition of macro 'SD_MOSI'
   35 | #define SD_MOSI       GPIO_NUM_40
      |                       ^~~~~~~~~~~
In file included from /home/maciek/d/ESP32-TUX/main/main.hpp:92:

Building with:

idf.py --version
ESP-IDF v5.1.3-dirty

**Comment by sukesh-ak** [comment]
Make sure to set the controller to `ESP32-S3` (for Plus) as per the readme file. I think your target MCU right now is `ESP32`.

Always use ESP-IDF released version only. 
Master branch is broken sometimes so unless you are planning to do bug fix for ESP-IDF you should not be using that.
