### ISSUE TITLE
Error building the project

### ISSUE THREAD

**Issue by umerkk** [sukesh-ak/ESP32-TUX#7]
Hi.
I am using ESP-IDF 5, and uncommented my device in main.hpp but i am getting this error when i run idf.py menuconfig.

![image](https://user-images.githubusercontent.com/16906595/207420532-ebee1d8f-22d5-4a06-8296-bdb571e5b29f.png)

**Comment by sukesh-ak** [comment]
Please read the steps in readme. 

You didn’t use recursive option when you cloned the repo.

**Comment by umerkk** [comment]
I did.. i did pasted the command posted in the ReadME

**Comment by umerkk** [comment]
![image](https://user-images.githubusercontent.com/16906595/207432448-99607403-7016-44bc-807e-6d8f5c21e74a.png)

![image](https://user-images.githubusercontent.com/16906595/207432487-5d2604b9-9a23-42fd-bad5-aea31cc7e27a.png)

**Comment by sukesh-ak** [comment]
Only other reason i can think of is that your path is too long. 

Clone it in c:\github or so.

**Comment by sukesh-ak** [comment]
Command for clone is this


git clone --recursive https://github.com/sukesh-ak/ESP32-TUX.git

**Comment by sukesh-ak** [comment]
If its ESP32-S3 device, you need to set the target as well.

**Comment by umerkk** [comment]
Yes the Long Path was an issue.. Thanks for assisting. it is working fine now.
